/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package soat;

/**
 *
 * @author CBN
 */
public class frmSOAT extends javax.swing.JFrame {

    /**
     * Creates new form frmSOAT
     */
    int tipoVehiculo;
    double cantAccidentes;
    boolean infraccion;
    SOAT soat = new SOAT();
    public frmSOAT() {
        initComponents();
        lbTotalPago.setText("");
        btnCalcular.setEnabled(false);
        txtCantidad.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rgVehiculo = new javax.swing.ButtonGroup();
        rgAccidentes = new javax.swing.ButtonGroup();
        rgInfracciones = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbCarro = new javax.swing.JRadioButton();
        rbMoto = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rbSIAccidente = new javax.swing.JRadioButton();
        rbNOAccidente = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbSIInfracciones = new javax.swing.JRadioButton();
        rbNOInfracciones = new javax.swing.JRadioButton();
        chkTerminos = new javax.swing.JCheckBox();
        btnCalcular = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lbTotalPago = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione tipo vehiculo");

        rgVehiculo.add(rbCarro);
        rbCarro.setText("Carro");
        rbCarro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        rgVehiculo.add(rbMoto);
        rbMoto.setText("Moto");
        rbMoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setText("Ha tenido accidentes de transito? ");

        rgAccidentes.add(rbSIAccidente);
        rbSIAccidente.setText("SI");
        rbSIAccidente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbSIAccidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSIAccidenteActionPerformed(evt);
            }
        });

        rgAccidentes.add(rbNOAccidente);
        rbNOAccidente.setText("NO");
        rbNOAccidente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbNOAccidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNOAccidenteActionPerformed(evt);
            }
        });

        jLabel3.setText("Cuantos?");

        jLabel4.setText("Ha tenido infraccion?");

        rgInfracciones.add(rbSIInfracciones);
        rbSIInfracciones.setText("SI");
        rbSIInfracciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        rgInfracciones.add(rbNOInfracciones);
        rbNOInfracciones.setText("NO");
        rbNOInfracciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        chkTerminos.setText("Acepto los terminos y condiciones");
        chkTerminos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chkTerminos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTerminosActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular Valor");
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnReset.setText("Recet");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lbTotalPago.setText("TOTAL");

        jLabel5.setText("Valor SOAT");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(rbCarro)
                            .addComponent(rbMoto))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbSIInfracciones)
                            .addComponent(jLabel4)
                            .addComponent(rbNOInfracciones)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnReset)
                        .addComponent(chkTerminos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbSIAccidente)
                                    .addComponent(rbNOAccidente))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbTotalPago)
                        .addGap(103, 103, 103))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnCalcular)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCarro)
                    .addComponent(rbSIInfracciones)
                    .addComponent(rbSIAccidente)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMoto)
                    .addComponent(rbNOInfracciones)
                    .addComponent(rbNOAccidente)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkTerminos)
                    .addComponent(lbTotalPago)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkTerminosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTerminosActionPerformed
        // TODO add your handling code here:
        btnCalcular.setEnabled(chkTerminos.isSelected());
    }//GEN-LAST:event_chkTerminosActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        enviarInfo();
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void rbSIAccidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSIAccidenteActionPerformed
        // TODO add your handling code here:
        cuturrulucantInfraccion();
    }//GEN-LAST:event_rbSIAccidenteActionPerformed

    private void rbNOAccidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNOAccidenteActionPerformed
        // TODO add your handling code here:
        cuturrulucantInfraccion();
    }//GEN-LAST:event_rbNOAccidenteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reseteamepapi();
    }//GEN-LAST:event_btnResetActionPerformed

    
    /**
     * @param args the command line arguments
     */
    private void seleccionVehiculo(){
        if (rbCarro.isSelected()) {
            tipoVehiculo = 1;
        }else{
            tipoVehiculo = 2;
        }
    }
    private void accidentes(){
        cantAccidentes = Double.parseDouble(txtCantidad.getText());
    }
    private void infraccion(){
        infraccion = rbSIInfracciones.isSelected();
    }
    private void cuturrulucantInfraccion(){
        if (rbSIAccidente.isSelected()) {
            txtCantidad.setEnabled(true);
            txtCantidad.setText("1");
        }else{
            txtCantidad.setEnabled(false);
            txtCantidad.setText("0");
        }
    }
    private void enviarInfo(){
        seleccionVehiculo();
        accidentes();
       
        lbTotalPago.setText("$"+soat.calcular(tipoVehiculo, cantAccidentes, infraccion));
    }
    private void reseteamepapi(){
        rgAccidentes.clearSelection();
        rgInfracciones.clearSelection();
        rgVehiculo.clearSelection();
        txtCantidad.setText("");
        txtCantidad.setEnabled(false);
        lbTotalPago.setText("");
        btnCalcular.setEnabled(false);
        chkTerminos.setSelected(false);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSOAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSOAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSOAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSOAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSOAT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox chkTerminos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbTotalPago;
    private javax.swing.JRadioButton rbCarro;
    private javax.swing.JRadioButton rbMoto;
    private javax.swing.JRadioButton rbNOAccidente;
    private javax.swing.JRadioButton rbNOInfracciones;
    private javax.swing.JRadioButton rbSIAccidente;
    private javax.swing.JRadioButton rbSIInfracciones;
    private javax.swing.ButtonGroup rgAccidentes;
    private javax.swing.ButtonGroup rgInfracciones;
    private javax.swing.ButtonGroup rgVehiculo;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
